POST http://localhost:3000/api/speakers HTTP/1.1
content-type: application/json

{
    "firstname": "Speaker 2 TEST",
    "lastname": "String",
    "email": "String",
    "title": "String",
    "company": "String",
    "phone": "String",
    "session": "String",
    "presentation": "String",
    "aboutme": "String",
    "photo": "image"
}

### get all speakers
GET http://localhost:3000/api/speakers HTTP/1.1

### Find by Id
GET http://localhost:3000/api/speakers/6682f02e09748d3822e17a52 HTTP/1.1

###
PUT http://localhost:3000/api/speakers HTTP/1.1
content-type: application/json

{
    "_id":"6682be2309748d3822e17767",
    "firstname": "CRUD UPDATE"
}

###
DELETE  http://localhost:3000/api/speakers?id=6682be8509748d3822e17770 HTTP/1.1
