POST http://localhost:3000/api/speakers HTTP/1.1
content-type: application/json

{
    "firstname": "Test",
    "lastname": "String",
    "email": "String",            
    "description": "String"
}

###
POST http://localhost:3000/api/speakers HTTP/1.1
content-type: application/json

{
    "firstname": "String",
    "lastname": "String",
    "email": "String",            
    "description": "String"
}

### get all speakers
GET http://localhost:3000/api/speakers HTTP/1.1

### Find by Id
GET http://localhost:3000/api/speakers/6681c39df6870d170140983d HTTP/1.1

###
PUT http://localhost:3000/api/speakers HTTP/1.1
content-type: application/json

{
    "_id":"6681c39df6870d170140983d",
    "firstname": "sim"
}

###
DELETE  http://localhost:3000/api/speakers?id=6681ae58cb5f3f436633a708 HTTP/1.1
