###
POST http://localhost:3000/api/users HTTP/1.1
content-type: application/json

{
    "name": "admin",
    "email": "admin@gmail.com",
    "password": "123456",
    "admin": true
}

###
POST http://localhost:3000/api/users HTTP/1.1
content-type: application/json

{
    "title": "New This 2",
    "description": "New description 2"
}

### get all users
GET http://localhost:3000/api/users HTTP/1.1

###
DELETE  http://localhost:3000/api/users?id=668eabc9fbc859ce3f0bd644 HTTP/1.1


### Find by Id
GET http://localhost:3000/api/users/6655d7a21448e198d4f93215 HTTP/1.1

###
PUT http://localhost:3000/api/users/665287411f6bb03a581b70b7 HTTP/1.1
content-type: application/json

{
    "newTitle": "Not Cancelled"
}


###
DELETE  http://localhost:3000/api/users?id=66991329f3cf912a705d3a23 HTTP/1.1